import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :viche, VicheWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl is disabled — TLS is terminated by the reverse proxy (e.g. Traefik).
# Enabling force_ssl when behind a proxy breaks internal Docker network WebSocket
# connections (Phoenix redirects HTTP→HTTPS before the WS upgrade can complete).
# If running without a reverse proxy, uncomment the block below:
#
# config :viche, VicheWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]],
#   exclude: [
#     hosts: ["localhost", "127.0.0.1"]
#   ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
